# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

env.aProgram('io_client', ['client.c'], LIBS=['simple_static', 'pthread', 'rt'])
env.aProgram('io_server', ['server.c'], LIBS=['simple_static', 'pthread', 'rt'])
