# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

env.Append(LIBPATH=['#/lib/'])

lib = [
    'simple_static',
    'rt',
]

env.aProgram(
    "array_list_unittest", 
    ['array_list_unittest.c'], 
    LIBS=lib)
