# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env.Append(CPPPATH='#/include/simple/')

obj = []
obj += Glob('*.c')
obj += Glob('file/*.c')
obj += Glob('collection/*.c')
obj += Glob('logging/*.c')
obj += Glob('io/*.c')
obj += Glob('cjson/*.c')

env.aStaticLibrary("simple_static", obj) 
env.aSharedLibrary("simple_shared", obj) 

env.aSubs('unittest')
