# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

env.Append(LIBPATH=['#/lib/'])

lib = [
    'simple_static',
    'rt',
]

env.aProgram(
    "timestamp_unittest", 
    ['timestamp_unittest.c'], 
    LIBS=lib)

#env.aProgram(
#    "memory_pool_unittest", 
#    ['memory_pool_unittest.c'], 
#    LIBS=lib)
#
#env.aProgram(
#    "cjson_unittest", 
#    ['cjson_unittest.c'], 
#    LIBS=['simple_static', 'm'])
#
#env.aProgram(
#    "array_list_unittest", 
#    ['array_list_unittest.c'], 
#    LIBS=['simple_static', 'm'])
